### ISSUE TITLE
Linux x86-64 binaries

### ISSUE THREAD

**Issue by fdcds** [kfwerf/delivery#1]
It would be great, if Linux x86-64 binaries could be provided for the releases.

**Comment by kfwerf** [comment]
i don't think i can do this as i do not own a linux machine and i can't target linux on a mac unfortunately, feel free to compile and add the releases here and i will include them

**Comment by nickelghost** [comment]
@kfwerf You can just use a virtual machine or even Docker containers for doing that.

**Comment by fdcds** [comment]
You can build using [CircleCI](https://circleci.com/). They support Windows, Linux and Mac and can build binaries for you (and run tests, etc).

**Comment by cosmotek** [comment]
I wouldn't mind helping with this.

**Comment by kfwerf** [comment]
could use the help!
